# docker-compose.yml
version: "3.8"

services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    network_mode: host
    restart: unless-stopped
    environment:
      - TURN_PUBLIC_IP=192.168.31.118
      - TURN_REALM=local
      - TURN_USERNAME=username
      - TURN_PASSWORD=password
      - TURN_MIN_PORT=40000
      - TURN_MAX_PORT=60000
    command: |
      --verbose
      --lt-cred-mech
      --no-tls
      --no-dtls
      --user=$${TURN_USERNAME}:$${TURN_PASSWORD}
      --realm=$${TURN_REALM}
      --external-ip=$${TURN_PUBLIC_IP}
      --listening-ip=0.0.0.0
      --relay-ip=0.0.0.0
      --listening-port=3478
      --tls-listening-port=5349
      --min-port=40000
      --max-port=60000
      --allowed-peer-ip=127.0.0.1
      --allowed-peer-ip=192.168.31.118/24
      --no-cli
      --no-multicast-peers
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/tcp"

    volumes:
      - ./coturn-data/certs:/etc/coturn/certs
      - ./coturn-data/turndb:/var/lib/coturn
